site_name: RƒÅpoi Cluster Documentation
nav: 
  - Documentation: index.md
  - Accessing the Cluster: accessing_the_cluster.md
  - Basic Commands: basic_commands.md
  - Storage and Quotas: storage.md
  - Using Paritions: partitions.md
  - Preparing your Environment: environment.md
  - Running Jobs: running_jobs.md
  - Connecting to Cloud Providers: cloud_providers.md
  - Managing Jobs: managaing_jobs.md
  - Using Containers: containers.md
  - Using Jupyter Notebooks: notebooks.md
  - Examples: examples.md 
  - Support: support.md
  - Utilisation: ganglia.md
  - Training: training.md


theme: readthedocs
markdown_extensions:
  - toc:
      permalink: True
      baselevel: 2
      toc_depth: 2

extra_css: [extra.css]

site_url: https://vuw-research-computing.github.io/raapoi-docs/